# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/archivers/php7-zip/Makefile 398632 2015-10-05 09:37:54Z ale $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-zip

.include "${MASTERDIR}/Makefile"
