# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php7-pdo_pgsql/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-pdo_pgsql

.include "${MASTERDIR}/Makefile"
