# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/ftp/php7-curl/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	ftp

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-curl

.include "${MASTERDIR}/Makefile"
