# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php7-pdo_sqlite/Makefile 384787 2015-04-26 12:33:09Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-pdo_sqlite

.include "${MASTERDIR}/Makefile"
