# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php7-mysqli/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-mysqli

.include "${MASTERDIR}/Makefile"
