# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/archivers/php7-bz2/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-bz2

.include "${MASTERDIR}/Makefile"
