# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php7-openssl/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-openssl

.include "${MASTERDIR}/Makefile"
