# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/converters/php7-iconv/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-iconv

.include "${MASTERDIR}/Makefile"
