# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/sysutils/php7-fileinfo/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-fileinfo

.include "${MASTERDIR}/Makefile"
